/*
 * @adonisjs/health
 *
 * (c) AdonisJS
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * Represents the result of a single health check execution
 *
 * @example
 * ```typescript
 * import { Result } from '@adonisjs/health'
 *
 * // Success result
 * const result: HealthCheckResult = {
 *   message: 'Database connection is healthy',
 *   status: 'ok',
 *   finishedAt: new Date(),
 *   meta: { responseTime: 120 }
 * }
 *
 * // Or using Result class
 * const result2 = Result.ok('Service is running')
 *   .setMetaData({ uptime: 86400 })
 *   .toJSON()
 * ```
 */
export type HealthCheckResult = {
  /**
   * A summary of the check result
   */
  message: string

  /**
   * The status of the check.
   */
  status: 'ok' | 'warning' | 'error'

  /**
   * Date/time when this check was completed
   */
  finishedAt: Date

  /**
   * An meta-data associated with the check
   */
  meta?: Record<string, any>
}

/**
 * The health check report generated by the health check runner.
 * Contains the overall status and results of all executed health checks.
 *
 * @example
 * ```typescript
 * import { HealthChecks } from '@adonisjs/health'
 * import { DiskSpaceCheck, MemoryHeapCheck } from '@adonisjs/health/checks'
 *
 * const healthChecks = new HealthChecks()
 * healthChecks.register([
 *   new DiskSpaceCheck().warnWhenExceeds(70).failWhenExceeds(85),
 *   new MemoryHeapCheck().warnWhenExceeds('200 mb')
 * ])
 *
 * const report: HealthCheckReport = await healthChecks.run()
 *
 * console.log(report.isHealthy) // true or false
 * console.log(report.status) // 'ok' | 'warning' | 'error'
 * console.log(report.checks.length) // 2
 * console.log(report.debugInfo.pid) // Process ID
 *
 * // Check individual results
 * report.checks.forEach(check => {
 *   console.log(`${check.name}: ${check.status}`)
 *   if (check.isCached) {
 *     console.log('Result was cached')
 *   }
 * })
 * ```
 */
export type HealthCheckReport = {
  /**
   * Is the entire report healthy. The value will be set to
   * false when one or more of the checks has a status or
   * "error"
   */
  isHealthy: boolean

  /**
   * Status of the entire report.
   *
   * - Set to "ok" when all checks have ok status
   * - Set to "warning" when one or more checks have warning status
   * - Set to "error" when one or more checks have error status
   */
  status: 'ok' | 'warning' | 'error'

  /**
   * The date/time when the entire report was computed
   */
  finishedAt: Date

  /**
   * The debugging info for the running process
   */
  debugInfo: {
    /**
     * The process id
     */
    pid: number

    /**
     * The process id for the parent process (if any)
     */
    ppid?: number

    /**
     * The number of seconds for which the process has been
     * running.
     */
    uptime: number

    /**
     * Node.js version
     */
    version: string

    /**
     * The platform on which the application is running
     */
    platform: string
  }

  /**
   * Perform checks and their report
   */
  checks: ({ isCached: boolean; name: string } & HealthCheckResult)[]
}

/**
 * Contract that all health checks must implement.
 * Defines the required properties and methods for a health check.
 *
 * @example
 * ```typescript
 * import { BaseCheck } from '@adonisjs/health'
 * import { Result } from '@adonisjs/health'
 * import type { HealthCheckContract, HealthCheckResult } from '@adonisjs/health/types'
 *
 * class DatabaseCheck extends BaseCheck implements HealthCheckContract {
 *   name = 'Database connection check'
 *   cacheDuration = 60 // Cache for 60 seconds
 *
 *   async run(): Promise<HealthCheckResult> {
 *     try {
 *       // Check database connection
 *       await database.raw('SELECT 1')
 *       return Result.ok('Database connection is healthy')
 *         .setMetaData({ connectionPool: database.pool.numUsed() })
 *     } catch (error) {
 *       return Result.failed('Database connection failed', error)
 *     }
 *   }
 * }
 *
 * // Usage
 * const dbCheck = new DatabaseCheck()
 * const result = await dbCheck.run()
 * ```
 */
export interface HealthCheckContract {
  /**
   * A unique name for the check
   */
  name: string

  /**
   * Whether to cache the results or not. The value must be
   * specified in seconds
   */
  cacheDuration?: number

  /**
   * The method to execute to perform the check
   */
  run(): Promise<HealthCheckResult>
}

/**
 * Tracing data shared with the health check channel subscribers
 */
export type HealthCheckTracingData = {
  check: HealthCheckContract
}
